export default {
  CHANGEABLE_OBJECTS: [
    'camera',
    'camera_base',
    'camera_base_2',
    'camera_frame',
    'base_frame',
    'base_frame_1',
    'base_frame_2',
    'base_frame_3',
    'base_inside',
    'sim_card',
    'base_1',
    'base_2',
    'base',
    'buttons',
    'buttons_2',
    'screen_base_1',
    'screen_base_3',
    'keyboard_base',
    'Capsule',
    'logo',
    'logo_top',
    'screen_base_bottom',
    'screen_bottom',
    'base_connection',
    'screen_element',
    'fingerprint',
    'base_bottom',
    'tablet_1',
    'phone_2',
    'mouse'
  ],
  SCREEN_OBJECT: ['screen', 'screen_2', 'screen_2_1', 'screen_basic'],
  SCREEN_BASE_OBJECT: [
    'screen_base_2',
    'screen_base',
    'screen_1',
    'screen_bottom'
  ],
  ROTATION_OBJECT: [
    'screen',
    'screen_base',
    'screen_base_bottom',
    'apple_logo',
    'apple_logo_1',
    'screen_bottom',
    'logo',
    'logo_top',
    'camera_base',
    'camera_screen',
    'camera',
    'camera_2',
    'screen_element',
    'base_frame',
    'camera_glass'
  ],
  ONE_COLOR_DEVICES: ['iphone-11', 'iphone-12', 'pixel', 'macbook', 'ipad'],
  WATERMARK_OBJECT: ['screen_base_2', 'screen_base', 'screen_1', 'screen_basic']
}
